### ISSUE TITLE
Add mailing feature

### ISSUE THREAD

**Issue by iamShantanu101** [awslabs/aws-ec2rescue-linux#18]
Folks, 

First of all, this is a nice utility.

There's just a suggestion/enhancement which you might agree to disagree.

It would be nice to have this send an email for `Diagnostic Results`.

This can be further configured. Like:

> Send email only if there are failures in the `Diagnostic Results`.

Obviously, we can always send emails using `mailx`,`sendmail`,etc. But it would be nice if a subcommand is added for sending conditional emails.

**Comment by gregbdunn** [comment]
Thanks for the kind words!

This is certainly something we can look into. I've got some initial concerns about deliverability, especially if just using your locally installed MTA, but it wouldn't be too much additional work to specify external servers/login details, I suppose.

**Comment by gregbdunn** [comment]
This didn't make it into 1.1, but we're still considering it for later versions.

**Comment by iamShantanu101** [comment]
Thanks for the update @gregbdunn.
