### ISSUE TITLE
Update botocore library that supports IMDSv2

### ISSUE THREAD

**Issue by ketanbhut** [awslabs/aws-ec2rescue-linux#60]
This is related to https://github.com/awslabs/aws-ec2rescue-linux/issues/58 
Current \lib\botocore\utils.py does not handle IMDSv2 - the file is updated in https://github.com/boto/botocore/blob/develop/botocore/utils.py - that handles IMDSv2. 
We should update our libraries.

**Comment by Drudenhaus** [comment]
Updated botocore and boto3 in commit f29ab319c5cc3e7511a855e6615760be39cbab33.
