### ISSUE TITLE
Amazon Linux 2 fails OpenSSH module key permissions check

### ISSUE THREAD

**Issue by gregbdunn** [awslabs/aws-ec2rescue-linux#66]
The default Amazon Linux 2 AMI fails the OpenSSH module check when examining the ed25519 key:
```
----------[Diagnostic Results]----------

module run/openssh [FAILURE] Improper configuration of one or more OpenSSH components.
-- SSH may deny access to users when improperly configured.
-- FAILURE Permission mode includes permissions for groups and/or other users: /etc/ssh/ssh_host_ed25519_key
-- Adjust permissions: sudo chmod 600 /etc/ssh/ssh_host_ed25519_key
```

Need to investigate and see why this is occurring. Not sure if this is a bug or the module is functioning correctly.

**Comment by Drudenhaus** [comment]
What are the permissions on the key? It should not have any bits set for group or other (as you may surmise from the recommended remediation permission mode).

[This](https://github.com/awslabs/aws-ec2rescue-linux/blob/develop/mod.d/openssh.yaml#L386) is the bitmask used to check the permissions:
```
sean@drudenhaus ~ $ python3
Python 3.8.3 (default, May 17 2020, 15:47:14) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stat
>>> bin(stat.S_IRWXG | stat.S_IRWXO)
'0b111111'
>>> oct(stat.S_IRWXG | stat.S_IRWXO)
'0o77'
>>> 
```

Here's the [code](https://github.com/awslabs/aws-ec2rescue-linux/blob/develop/mod.d/openssh.yaml#L1611) for creating the graph nodes for the host keys.

**Comment by gregbdunn** [comment]
```
module run/openssh               [FAILURE] Improper configuration of one or more OpenSSH components.
                                 -- SSH may deny access to users when improperly configured.
                                 -- FAILURE     Permission mode includes permissions for groups and/or other users: /etc/ssh/ssh_host_rsa_key
                                 --             Adjust permissions:   sudo chmod 600 /etc/ssh/ssh_host_rsa_key
                                 -- FAILURE     Permission mode includes permissions for groups and/or other users: /etc/ssh/ssh_host_ecdsa_key
                                 --             Adjust permissions:   sudo chmod 600 /etc/ssh/ssh_host_ecdsa_key
                                 -- FAILURE     Permission mode includes permissions for groups and/or other users: /etc/ssh/ssh_host_ed25519_key
                                 --             Adjust permissions:   sudo chmod 600 /etc/ssh/ssh_host_ed25519_key
```


ls:

```
[root@ip-172-16-1-223 aws-ec2rescue-linux]# ls -l /etc/ssh/ssh_host_*_key
-rw-r----- 1 root ssh_keys  227 Dec 19  2017 /etc/ssh/ssh_host_ecdsa_key
-rw-r----- 1 root ssh_keys  387 Dec 19  2017 /etc/ssh/ssh_host_ed25519_key
-rw-r----- 1 root ssh_keys 1679 Dec 19  2017 /etc/ssh/ssh_host_rsa_key
```

**Comment by gregbdunn** [comment]
Apparently /usr/libexec/openssh/ssh-keysign uses the ssh_keys group, and that is why these are 640. We'll probably see this on Cent/Rhel 8 as well.

**Comment by gregbdunn** [comment]
Actually, we see this on rhel7.8 as well:

```
[ec2-user@ip-172-16-1-14 ~]$ ls -l /etc/ssh/ssh_host_*_key
-rw-r-----. 1 root ssh_keys  227 Dec  7  2016 /etc/ssh/ssh_host_ecdsa_key
-rw-r-----. 1 root ssh_keys  387 Dec  7  2016 /etc/ssh/ssh_host_ed25519_key
-rw-r-----. 1 root ssh_keys 1675 Dec  7  2016 /etc/ssh/ssh_host_rsa_key
```

Looks like the change was made around OpenSSH 8.1

**Comment by gregbdunn** [comment]
```
[root@ip-172-16-1-223 ~]# lid -g ssh_keys
[root@ip-172-16-1-223 ~]# lid -g wheel
 ec2-user(uid=1000)
```

Group is empty. The change appears to actually just be a packaging change for some distros - modern versions of debian, etc., are still 600/root group.

We don't have any handling built into ec2rl for tracking this sort of thing, so it would have to be done in module.

We could try to figure out exact package versions when it changed, but that seems to be.... significant effort.

We could check to see if it's 600, or 640 w/ ssh_keys as the group. This opens up to some edge case false positives/false negatives, but I think they're likely to be rare enough that they aren't super concerning.

**Comment by Drudenhaus** [comment]
[WIP branch](https://github.com/awslabs/aws-ec2rescue-linux/compare/develop...Drudenhaus:issue%2366)

**Comment by Drudenhaus** [comment]
Looks like anything picking up changes from [Fedora](https://src.fedoraproject.org/rpms/openssh/blob/master/f/sshd-keygen) will likely inherit this permission mode behavior. Not sure of the best way to determine whether this is "ok" for a given system without more research.
